"""more user roles

Revision ID: 0579d861c85e
Revises: ef00b4f232c1
Create Date: 2025-04-04 13:54:43.925739

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0579d861c85e"
down_revision: str | None = "ef00b4f232c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=5),
            type_=sa.Enum(
                "admin", "basic", "participant", "viewer", name="userrole"
            ),
            existing_nullable=False,
            existing_server_default=sa.text("'basic'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum(
                "admin", "basic", "participant", "viewer", name="userrole"
            ),
            type_=sa.VARCHAR(length=5),
            existing_nullable=False,
            existing_server_default=sa.text("'basic'"),
        )

    # ### end Alembic commands ###
