"""change username to email

Revision ID: c3d858a62990
Revises: 676c12c745d5
Create Date: 2025-04-02 18:08:08.110373

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3d858a62990"
down_revision: str | None = "676c12c745d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.drop_column("user", "password")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
